spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: .19961128ai
    url: jdbc:mysql://127.0.0.1/db_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level: debug
#    com.zero.SellApplicationTests: info

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
